name: Check new java libraries (JARs) and release them

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: The name of the product to be released.
      lp-building-project:
        required: true
        type: string
        description: The LP build project of the building project.
      lp-building-repo:
        required: true
        type: string
        description: The relative path to the LP git repo of the Product to be released.
      lp-building-branch-prefix:
        required: true
        type: string
        description: The prefix of the LP Git branches producing builds of the Product to be released.
      lp-consumer-key:
        required: true
        type: string
        description: The consumer key used to authenticate with Launchpad.
      lp-access-token:
        required: true
        type: string
        description: The access token used to authenticate with Launchpad.
      lp-access-secret:
        required: true
        type: string
        description: The access secret used to authenticate with Launchpad.
      library-regex:
        required: true
        type: string
        description: The regular expression to extract name of the library.

env:
  LP_CREDENTIALS: credentials.txt
  OUTPUT_DIR: output

jobs:
  download-builds:
    name: Download build library from Launchpad
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print passed vars
        run: |
          echo "name: ${{ inputs.name }}"
          echo "lp-building-project: ${{ inputs.lp-building-project }}"
          echo "lp-building-repo: ${{ inputs.lp-building-repo }}"
          echo "lp-building-branch-prefix: ${{ inputs.lp-building-branch-prefix }}"
          echo "library-regex: ${{ inputs.library-regex }}"

      - name: Create credentials file for Launchpad
        env:
          CONSUMER_KEY: ${{ secrets[inputs.lp-consumer-key] }}
          ACCESS_TOKEN: ${{ secrets[inputs.lp-access-token] }}
          ACCESS_SECRET: ${{ secrets[inputs.lp-access-secret] }}
        run: |
          cat <<EOF >> ${{ env.LP_CREDENTIALS }}
          [1]
          consumer_key = ${CONSUMER_KEY}
          consumer_secret = 
          access_token = ${ACCESS_TOKEN}
          access_secret = ${ACCESS_SECRET}
          EOF

      - name: Install Python dependencies for Launchpadapi lib
        run: pip install -r requirements.txt

      - name: Create folder for storing the downloaded artifacts
        run: mkdir "${{ env.OUTPUT_DIR }}"

      - name: Download the most recent built libraries from Launchpad
        run: |
          python3 -m uploader.launchpad_downloader \
            --repository-url ${{ inputs.lp-building-repo }} \
            --branch-prefix ${{ inputs.lp-building-branch-prefix }} \
            --credential-file ${{ env.LP_CREDENTIALS }} \
            --output-folder ${{ env.OUTPUT_DIR }}
      
      - name: Check if products needed to be released
        id: check-release
        run: |
          python3 -m uploader.services \
            check-library-releases \
            --output-directory ${{ env.OUTPUT_DIR }} \
            --library-pattern ${{ inputs.library-regex }} \
            --repository-owner canonical --project-name ${{ github.event.repository.name }}
          
          cd ${{ env.OUTPUT_DIR }};
          number_of_releases=$( ls . | wc -l )
          echo "Number of remaining releases: $number_of_releases"
          if [ $number_of_releases -lt 1 ]; then
            echo "Nothing to update!"
            echo "release-package=false" > $GITHUB_OUTPUT
            exit 0
          else
            # set output release to true
            echo "release-package=true" > $GITHUB_OUTPUT
          fi

      - name: List downloaded builds and compress them
        run: ls ${{ env.OUTPUT_DIR }}; zip -r ${{ env.OUTPUT_DIR }}-${{ inputs.name }}.zip ${{ env.OUTPUT_DIR }}

      - name: Store builds
        if: ${{ steps.check-release.outputs.release-package == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: releases-${{ inputs.name }}-${{ inputs.lp-building-branch-prefix }}
          path: ${{ env.OUTPUT_DIR }}-${{ inputs.name }}.zip

      - name: Generate matrix with all built versions
        if: ${{ steps.check-release.outputs.release-package == 'true' }}
        id: set-matrix
        run: |
          echo "matrix=$(ls -A1 ${{ env.OUTPUT_DIR }} | jq -R -s -c 'split("\n")[:-1]')" > $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      release: ${{ steps.check-release.outputs.release-package }}

  release-artifact:
    if: ${{ needs.download-builds.outputs.release == 'true' }}
    name: Release library on Github
    needs: download-builds
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.download-builds.outputs.matrix) }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download releases
        uses: actions/download-artifact@v3
        with:
          name: releases-${{ inputs.name }}-${{ inputs.lp-building-branch-prefix }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Decompress all versions and list them
        run: |
          unzip ${{ env.OUTPUT_DIR }}-${{ inputs.name }}.zip 
          ls "${{ env.OUTPUT_DIR }}"

      - name: Get library name and software version
        id: get-library-name
        run: |
          cd output/${{ matrix.version }}/
          count=$( ls ${{ inputs.library-regex }} | wc -l )
          if [ $count != 1 ]; then
            echo "Library file not found with regex: ${{ inputs.library-regex }}"
            exit 1
          fi
          library_filename=$(ls ${{ inputs.library-regex }})
          echo "LIBRARY FILENAME: $library_filename"
          echo "LIBRARY_FILENAME=$library_filename" >> $GITHUB_OUTPUT
          version=$(echo "${library_filename%.*}")
          echo "VERSION: $version"
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          cd ../../
          ls

      - name: Release the package on Github
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.get-library-name.outputs.VERSION }}
          tag_name: ${{ steps.get-library-name.outputs.VERSION }}

      - name: Upload library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ env.OUTPUT_DIR }}/${{ matrix.version }}/${{ steps.get-library-name.outputs.LIBRARY_FILENAME }}
          asset_name: ${{ steps.get-library-name.outputs.LIBRARY_FILENAME }}
          asset_content_type: application/zip

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: output/${{ matrix.version }}/${{ steps.get-library-name.outputs.LIBRARY_FILENAME }}.sha512
          asset_name: ${{ steps.get-library-name.outputs.LIBRARY_FILENAME }}.sha512
          asset_content_type: application/txt
