name: Release CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  workflow_call:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create matrix
        id: set-matrix
        run: |
          cat products.json
          echo "matrix=$(cat libraries.json | jq -c)" > $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 

  release-products:
    secrets: inherit
    uses: ./.github/workflows/check-new-java-libraries.yaml
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: 
        product: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
              
    with:
      name: ${{ matrix.product.name }}
      lp-building-project: ${{ matrix.product.lp-building-project }}
      lp-building-repo: ${{ matrix.product.lp-building-repo }}
      lp-building-branch-prefix: ${{ matrix.product.lp-building-branch-prefix }}
      lp-consumer-key: ${{ matrix.product.lp-consumer-key }}
      lp-access-token: ${{ matrix.product.lp-access-token }}
      lp-access-secret: ${{ matrix.product.lp-access-secret }}
      library-regex: ${{ matrix.product.library-regex }}
